---
- name: nginx "install & start service"
  hosts: all
  become: true
  
  tasks:
  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "Enable nginx"
    service:
      name=nginx
      enabled=yes
    become: yes

  handlers:
    - name: "restart nginx"
      service:
        name=nginx
        state=restarted